import { useEffect, useState } from "react";
import { ResearchStudio } from "@/components/ResearchStudio";
import { getHealth } from "@/lib/api";

export default function App() {
  const [modelLabel, setModelLabel] = useState<string | null>(null);

  useEffect(() => {
    getHealth().then((h) => {
      if (h?.llm_model) setModelLabel(h.llm_model.replace(/:free$/, ""));
    });
  }, []);

  return (
    <main className="mx-auto max-w-6xl px-4 py-10 md:py-14">
      <header className="mb-10 max-w-3xl">
        <p className="text-sm font-semibold uppercase tracking-[0.2em] text-accent">SourceBrief</p>
        <h1 className="mt-3 font-display text-4xl font-bold leading-tight md:text-5xl">
          Sourced equity research, run by agents.
        </h1>
        <p className="mt-4 text-lg text-ink/75">
          Planner → Workers → Critic for <span className="font-semibold">Indian equities (NSE/BSE)</span>
          {modelLabel ? (
            <>
              , powered by <span className="font-semibold">{modelLabel}</span>
            </>
          ) : null}
          . Enter a ticker for INR price action, fundamentals, India news sentiment, results
          highlights, and flagged risks — every claim linked to a source.
        </p>
      </header>
      <ResearchStudio />
      <footer className="mt-14 border-t border-line pt-6 text-sm text-ink/50">
        Research briefs are generated by AI agents from public data (Yahoo Finance, Tavily news
        search) and are not investment advice. Verify claims via the cited sources.
      </footer>
    </main>
  );
}
